stages:
  complete-ingatlan:
    cmd: dz run-step ingatlan complete
    deps:
    - src/ingatlan.py
    params:
    - zimmer.yaml:
      - aswan_projects.ingatlan.current_leaf
    outs:
    - data/tempartifact/ingatlan/complete:
        persist: true
